http:
  routers:
     downstream:
       rule: "PathPrefix(`/`)"
       service: "downstream"

  services:
    downstream:
      loadBalancer:
        servers:
        - url: "DOWNSTREAM_SCHEME://DOWNSTREAM_ADDRESS:DOWNSTREAM_PORT"
