http:
  serversTransports:
    mytransport:
      insecureSkipVerify: true

  routers:
     downstream:
       rule: "PathPrefix(`/`)"
       service: "downstream"

  services:
    downstream:
      loadBalancer:
        servers:
        - url: "DOWNSTREAM_SCHEME://DOWNSTREAM_ADDRESS:DOWNSTREAM_PORT"

tls:
  stores:
    default:
       defaultCertificate:
          certFile: /etc/testCert.crt
          keyFile:  /etc/testCert.key
      